services:
  tls-termination-proxy:
    container_name: tls-termination-proxy
    image: nginx
    networks:
      - sedlab
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=143.198.251.72
      - NGINX_PORT=443
    build:
      context: ./deployment/nginx/
      dockerfile: Dockerfile-tls-termination-proxy
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - "core-db"
      - "backend-api"
