services:
  tls-termination-proxy:
    container_name: tls-termination-proxy
    image: nginx
    networks:
      - sedlab
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=imspc063247.ppd.chalmers.se
      - NGINX_PORT=443
    build:
      context: ./nginx/
      dockerfile: Dockerfile-tls-termination-proxy
    volumes:
      - C:\Certbot\live\imspc063247.ppd.chalmers.se\:/etc/nginx/certs/live/imspc063247.ppd.chalmers.se # TLS Certs syslink location
      - C:\Certbot\archive\imspc063247.ppd.chalmers.se\:/etc/nginx/certs/archive/imspc063247.ppd.chalmers.se # TLS Certs actual location
    depends_on:
      - "core-db"
      - "backend-api"
