services:
  tls-termination-proxy:
    container_name: tls-termination-proxy
    networks:
      - sedlab
    ports:
      - "443:443"
    build:
      context: ./nginx/
      dockerfile: Dockerfile-tls-termination-proxy
    restart: on-failure
    volumes:
      - C:\Certbot\live\imspc063247.ppd.chalmers.se\:/etc/ssl/certs # TLS Certs location
    depends_on:
      - "core-db"
      - "backend-api"