services:

  core-db:
    container_name: core-db
    networks:
      - sedlab
    ports:
      - "3001:3306"
    build:
      context: ./apps/core/
      dockerfile: Dockerfile-core-db
    restart: on-failure
    volumes:
      - persistent-volume:/var/lib/mysql

  backend-api:
    container_name: backend-api
    networks:
      - sedlab
    ports:
      - "8000:80"
    build:
      context: .
      dockerfile: Dockerfile-backend-api
    restart: on-failure
    depends_on:
      - "core-db"

networks:
  sedlab:             # Ensures that all containers can communicate on the same virtual network

volumes:
  persistent-volume:  # Stores database even if the containers are restarted
